#!/bin/bash

export HADOOP_HOME=${HADOOP_HOME:-/usr/yava/3.1.0.0-0000/hadoop}
export HADOOP_MAPRED_HOME=${HADOOP_MAPRED_HOME:-/usr/yava/3.1.0.0-0000/hadoop-mapreduce}
export HADOOP_YARN_HOME=${HADOOP_YARN_HOME:-/usr/yava/3.1.0.0-0000/hadoop-yarn}
export HADOOP_LIBEXEC_DIR=${HADOOP_HOME}/libexec
export YAVA_VERSION=${YAVA_VERSION:-3.1.0.0-0000}
export HADOOP_OPTS="${HADOOP_OPTS} -Dyava.version=${YAVA_VERSION}"

exec /usr/yava/3.1.0.0-0000/hadoop-hdfs/bin/hdfs.distro "$@"
